### ISSUE TITLE
Need requirements or environment file for the notebooks

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#113]
In https://github.com/QuantEcon/lecture-datascience.notebooks  it is missing the Requirements.txt file (or conda equivalent).

Thinks like binder won't really work well without it (nor can the `.devcontainer` )

Just to be clear, this is **not** the same as the environment for the editing of the environment itsel.f  i.e. https://github.com/QuantEcon/lecture-datascience.myst/blob/main/environment.yml  is for the jupyterbook and not end-users.

I can imagine something like
```yaml
name: lecture-datascience-notebooks
channels:
  - default
dependencies:
  - python=3.8
  - anaconda=2020.11
  - pip
  - pip:
    - interpolation
    - qeds 
    - fiona 
    - geopandas 
    - pyLDAvis >= 3.3.0
    - gensim 
    - folium 
    - descartes 
    - pyarrow
    - xgboost
    - graphviz
    - scikit-learn >= 0.24.0
    - bokeh
    - nltk
  - conda:
    - python-graphviz
```
etc.  i.e. no latex or sphinx stuff.

If there is no easy way to maintain this file in the `.myst` source repo, then we can just maintain it in the notebook repo itself.
