### ISSUE TITLE
Add devcontainer for the notebook repo to source control (for codespaces and vscode remote options)

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#183]
Current there is a test branch directly on the notebook repo: https://github.com/QuantEcon/lecture-datascience.notebooks/tree/devcontainer-test/.devcontainer

- [ ] This folder and files should be in https://github.com/QuantEcon/lecture-datascience.myst/tree/main/_notebook_repo  in a `.devcontainer` folder
- [ ] We should make sure these correctly deploy to the root of that notebook repo (i.e. inside of https://github.com/QuantEcon/lecture-datascience.notebooks/tree/main/ in the deployment)
- [ ] Close that old test branch when complete.

@mmcky  and @Alim-faraji  Is that possible?  We don't want to maintain those files in the notebook repo separately.

**Comment by jlperla** [comment]
@jbrightuniverse   FYI.  You can test when this is complete and these are deployed to the repo.

**Comment by mmcky** [comment]
@jlperla absolutely. The `_notebook_repo` is the best spot for it as `github actions` builds the `notebooks repo` and then pushes it during the `publish.yml` workflow.

**Comment by jlperla** [comment]
Great.  Is this something that @jbrightuniverse and @Alim-faraji can do on their own?  Does he just need to put the files in there and they automatically copy over?

**Comment by mmcky** [comment]
basically -- and harmonise with `lecture-python.myst` action by adding the work to sync the generated notebooks to the repo in `publish.yml`

```
      - name: Prepare lecture-python.notebooks sync
        shell: bash -l {0}
        run: |
          mkdir -p _build/lecture-python.notebooks
          cp -a _notebook_repo/. _build/lecture-python.notebooks
          cp _build/jupyter/*.ipynb _build/lecture-python.notebooks
          ls -a _build/lecture-python.notebooks
      - name: Commit latest notebooks to lecture-python.notebooks
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.QUANTECON_SERVICES_PAT }}
        with:
          source-directory: '_build/lecture-python.notebooks/'
          destination-repository-username: 'QuantEcon'
          destination-repository-name: 'lecture-python.notebooks'
          commit-message: 'auto publishing updates to notebooks'
          destination-github-username: 'quantecon-services'
          user-email: services@quantecon.org
```
I will need to add the `QUANTECON_SERVICES_PAT` to push to the repo.
